"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { ReactNode } from "react";

const nav = [["/home","Home","01"],["/learn/phase-1/causal-attention","Learn","02"],["/lab/phase-1/causal-attention","Lab","03"],["/research/journal","Research","04"],["/progress/phase-1","Progress","05"]] as const;
function routeContext(pathname:string){if(pathname.startsWith("/learn"))return{path:"Phase 1 · Build / Learn",objective:"Understand causal GQA and connect equations to tensor shapes.",state:"Learning"};if(pathname.startsWith("/lab"))return{path:"Phase 1 · Build / Lab",objective:"Implement causal GQA and produce correctness evidence.",state:"Implementing"};if(pathname.startsWith("/experiments"))return{path:"Phase 1 · Build / Experiment",objective:"Measure how naïve attention memory scales with sequence length.",state:"Experimenting"};if(pathname.startsWith("/research"))return{path:"Phase 1 · Build / Research",objective:"Preserve prediction, evidence, interpretation and uncertainty.",state:"Research"};if(pathname.startsWith("/progress"))return{path:"Phase 1 · Build / Progress",objective:"Audit which mastery evidence is complete and what remains.",state:"Awaiting mastery"};if(pathname.startsWith("/setup"))return{path:"Technical onboarding",objective:"Qualify the local research environment and execution profile.",state:"Setup"};return{path:"Phase 1 · Build",objective:"Continue the current evidence-producing learning loop.",state:"Experimenting"}}

export function AppShell({children, operational}:{children:ReactNode;operational:{vramGiB:number|null;precision:string|null;profile:string|null;commit:string|null;experiment:string|null;masteryCount:number}}){const pathname=usePathname();const context=routeContext(pathname);const activeRoot=nav.find(([href])=>pathname.startsWith(href.split("/").slice(0,2).join("/")))?.[0];return <div className="app-shell"><header className="topbar"><Link className="wordmark" href="/home" aria-label="First Principles LLM Research home">FP<span>LLM</span></Link><div className="topbar-center"><span className="context-path">{context.path}</span><button className="ghost-button" type="button">Search / ⌘K</button></div><div className="topbar-actions"><Link className="compute-chip" href="/setup/compute"><span className="compute-dot" />{operational.vramGiB ?? "—"} GB · {(operational.precision??"—").toUpperCase()}</Link><span className="sync-label small muted">DB ✓</span><form action="/auth/logout" method="post"><button className="ghost-button" type="submit">Sign out</button></form></div></header><div className="app-grid"><nav className="primary-nav" aria-label="Primary"><ul className="nav-list">{nav.map(([href,label,index])=>{const current=activeRoot===href||pathname===href;return <li key={href}><Link className="nav-link" aria-current={current?"page":undefined} href={href}><span>{label}</span><span className="nav-index">{index}</span></Link></li>})}</ul><div className="nav-secondary"><Link className="nav-link" href="/setup/compute"><span>Compute</span><span className="nav-index">GPU</span></Link><Link className="nav-link" href="/setup/repository"><span>Repository</span><span className="nav-index">Git</span></Link></div></nav><main className="workspace">{children}</main><aside className="context-panel"><div className="context-group"><p className="context-label">Current objective</p><p className="context-value">{context.objective}</p></div><div className="context-group"><p className="context-label">State</p><p className="context-value">{context.state}</p></div><div className="context-group"><p className="context-label">Compute</p><p className="context-value">{operational.profile??"—"}<br/>{operational.precision??"—"}</p></div><div className="context-group"><p className="context-label">Evidence</p><p className="context-value mono">commit {operational.commit??"—"}<br/>experiment {operational.experiment??"—"}</p></div><div className="context-group"><p className="context-label">Mastery</p><p className="context-value">{operational.masteryCount} of 6 requirements complete</p></div></aside></div><footer className="statusbar"><span>Course v1.0 · Unit v1.0 · Lab v1.0</span><span>PostgreSQL evidence · Private research artifacts</span></footer></div>}
